const events = [
    {   eventId : 1,
        timestamp : new Date('2023-11-27T01:05:00'),
        title : 'Open AI : GPT-4 Launch Seminar',
        eventBy : 'OpenAI',
        location : 'offline',
        invitationType : 'invited',
        imgLocation : '/images/metroEventsLogo.png',
    },
    {   eventId : 2,
        timestamp : new Date('2023-11-20T12:23:00'),
        title : 'Weekly Coding Contest : 102',
        eventBy : 'LeetCode',
        location : 'virtual',
        invitationType : 'registered',
        imgLocation : '/images/programming.png',
    },
    {   eventId : 3,
        timestamp : new Date('2023-11-15T03:33:00'),
        title : 'BBQ Free Buffet : Couples Only',
        eventBy : 'BBQ',
        location : 'offline',
        invitationType : 'invited',
        imgLocation : '/images/restaurant.png',
    },
    {   eventId : 4,
        timestamp : new Date('2023-11-28T05:30:00'),
        title : 'Master Data Structure weekly class',
        eventBy : 'Striver',
        location : 'virtual',
        invitationType : 'registered',
        imgLocation : '/images/datastructure.png',
    },
]

export default events;